import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
const root=resolve(import.meta.dirname,'..');
const thermal=process.argv.includes('--thermal');
const combined=process.argv.includes('--combined');
const rootNetwork=process.argv.includes('--root-network');
const passage=process.argv.includes('--passage');
const escort=process.argv.includes('--escort');
const resonance=process.argv.includes('--resonance');
const graphical=process.argv.includes('--graphical');
const stamp=new Date().toISOString().replace(/[:.]/g,'-');
const evidence=resolve(root,'evidence',`journey-${graphical?'graphical':'headless'}-${stamp}`);
mkdirSync(evidence,{recursive:true});
const engine=process.env.GODOT_BIN || 'C:/Users/tsang/AppData/Local/Microsoft/WinGet/Packages/GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe/Godot_v4.7.2-stable_win64_console.exe';
const args=[...(graphical?['--resolution','1440x900']:['--headless']),'--path',resolve(root,'godot'),'--script',thermal?'res://tests/thermal_drive.gd':combined?'res://tests/combined_drive.gd':'res://tests/survey_drive.gd','--',...(thermal?['--thermal']:rootNetwork?['--root-network']:passage?['--passage']:escort?['--escort']:(resonance?['--resonance']:['--full-route'])),'--evidence-dir='+evidence];
const provenanceFiles=['godot/project.godot','godot/main.tscn',...readdirSync(resolve(root,'godot/scripts')).filter(f=>f.endsWith('.gd')).sort().map(f=>'godot/scripts/'+f),thermal?'godot/tests/thermal_drive.gd':combined?'godot/tests/combined_drive.gd':'godot/tests/survey_drive.gd'];
const sourceCommit=spawnSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).stdout?.trim();
const sourceHashes=Object.fromEntries(provenanceFiles.map(f=>[f,createHash('sha256').update(readFileSync(resolve(root,f))).digest('hex')]));
writeFileSync(resolve(evidence,'provenance.json'),JSON.stringify({sourceCommit,sourceHashes},null,2));
const start=Date.now();
const r=spawnSync(engine,args,{encoding:'utf8',timeout:combined?1830000:930000,maxBuffer:4*1024*1024});
writeFileSync(resolve(evidence,'stdout.log'),r.stdout||'');
writeFileSync(resolve(evidence,'stderr.log'),r.stderr||'');
let receipt=null;
try { receipt=JSON.parse(readFileSync(resolve(evidence,'drive.json'),'utf8')); } catch {}
const passed=r.status===0 && !r.error && receipt?.passed===true;
const result={passed,sourceCommit,sourceHashes,routePassed:receipt?.routePassed??false,fullRouteRequested:receipt?.fullRouteRequested??true,visualCaptureStatus:receipt?.visualCaptureStatus??"incomplete",routeSeconds:receipt?.seconds??null,evidence,wallSeconds:(Date.now()-start)/1000,exitCode:r.status,error:r.error?.message??null,rendering:graphical?'graphical':'headless',stage:receipt?.stage??'no_receipt',args};
writeFileSync(resolve(evidence,'runner.json'),JSON.stringify(result,null,2));
console.log(JSON.stringify(result,null,2));
process.exit(passed?0:1);
